function [ThrustRatio] = f_ThrustRatio_TP_CRUISE(AircraftData, Mach, Altitude_ft, Throttle)

% Break-points: 6 x 52 x 7
% Throttle: [0.2,0.3,0.4,0.75,0.95,1];
% Mach: linspace(0,0.6,52);
% Altitude_ft: [0 5000 10000 15000 20000 25000 30000];

[m_Throttle, m_MACH, m_Altitude_ft] = ndgrid( ...
    AircraftData.Propulsion.Interp.v_Throttle_Thrust_CRUISE_bp, ...    
    AircraftData.Propulsion.Interp.v_Mach_Thrust_CRUISE_bp, ...
    AircraftData.Propulsion.Interp.v_h_ft_Thrust_CRUISE_bp);

ThrustRatio = interpn( ...
    m_Throttle, m_MACH, m_Altitude_ft, ...
        AircraftData.Propulsion.Interp.Thrust_Ratio_Interp_CRUISE, ...
    Throttle, Mach, Altitude_ft, 'spline');

end