function [TSFC] = f_TSFC_TP_TO(AircraftData, Mach, Altitude_ft)

[m_Mach, m_Altitude_ft] = meshgrid( ...
    AircraftData.Propulsion.Interp.v_Mach_Thrust_TO_bp, ...
    AircraftData.Propulsion.Interp.v_h_ft_Thrust_TO_bp);

TSFC = interp2( ...
    m_Mach, m_Altitude_ft, ...
        AircraftData.Propulsion.Interp.TSFC_Interp_TO, ...
    Mach, Altitude_ft);

end