function [TSFC] = f_TSFC_TP_CLIMB(AircraftData, Mach, Altitude_ft)

[m_Mach, m_Altitude_ft] = meshgrid( ...
    AircraftData.Propulsion.Interp.v_Mach_Thrust_CLIMB_bp, ...
    AircraftData.Propulsion.Interp.v_h_ft_Thrust_CLIMB_bp);

TSFC = interp2( ...
    m_Mach, m_Altitude_ft, ...
        AircraftData.Propulsion.Interp.TSFC_Interp_CLIMB, ...
    Mach, Altitude_ft);

end