close all; clear; clc

myAircraft = load('f18harvthrust.mat');

ModelsInputs = zeros(1, 11);
delta_e_deg_cases = -20 : 5 : 10;

liftCharacteristicsPlot(myAircraft, ModelsInputs, [-5, 40], ...
                delta_e_deg_cases, 'exf18harvthrustliftcharacteristics.pdf')

staticPolarPlot(myAircraft, ModelsInputs, [-5, 40], ...
                delta_e_deg_cases, 'exf18harvthrustdragcharacteristics.pdf')

q_degps_cases = linspace(-10, 15, 6);
pitchCharacteristicsPlot(myAircraft, ModelsInputs, [-5, 40], ...
                     delta_e_deg_cases, q_degps_cases, ...
                     'exf18harvthrustpitchcharacteristics.pdf')

h_cases = 0 : 2000 : 12000;
Mach_cases = 0.20 : 0.30 : 2.0;
thrustCharacteristicsPlot(myAircraft, [0, 12000], [0, 2], ...
                          h_cases, Mach_cases, ...
                          'exf18harvthrustthrustcharacteristics1.pdf', ...
                          'exf18harvthrustthrustcharacteristics2.pdf', ...
                          'exf18harvthrustthrustcharacteristics3.pdf')

t_end = 10;

x_EG0 = 0;
y_EG0 = 0;
z_EG0 = -8000;

Mach0 = 0.8;
[temp0, sound0, press0, dens0] = atmosisa(-z_EG0);
V0 = Mach0 * sound0;

phi0 = 0;
theta0 = convang(-2.5, 'deg', 'rad');
psi0 = 0;
Quat0 = angle2quat(psi0, theta0, phi0);

alpha0_deg = 9.5; alpha0 = convang(alpha0_deg, 'deg', 'rad');
beta0_deg = 0; beta0 = convang(beta0_deg, 'deg', 'rad');

p0 = 0;
q0 = 0;
r0 = 0;

state0 = [V0, alpha0, beta0, p0, q0, r0, x_EG0, y_EG0, z_EG0, Quat0].';

delta_T0 = 0.45;
delta_T_law = @(t) interp1([0, 0.33, 0.67, 2] * t_end/2, ...
                           [1, 0.8, 1.8, 2] * delta_T0, ...
                            t, 'pchip');

delta_e0_deg = -8.5;
delta_e_deg_law = @(t) interp1( ...
                [0, 0.33, 0.67,  1] * t_end, ...
                [1.5, 1, 1.8,  2] * delta_e0_deg, ...
                 t, 'pchip');

delta_s0_deg = 0;
delta_s_deg_law = @(t) interp1([0, 1] * t_end, ...
                               [1, 1] * delta_s0_deg, ...
                                t, 'linear');

delta_a0_deg = -12.5;
delta_a_deg_law = @(t) interp1([0, 0.33, 0.67, 2] * t_end/2, ...
                               [1, 0, 0, 0] * delta_a0_deg, ...
                                t, 'pchip');

delta_r0_deg = -10;
delta_r_deg_law = @(t) interp1([0, 0.33, 0.67, 1] * t_end, ...
                               [1, 0, 0, 0] * delta_r0_deg, ...
                                t, 'pchip');

[time, ...
 delta_T, delta_e_deg, delta_s_deg, delta_a_deg, delta_r_deg, ...
 V, alpha, beta, p, q, r, ...
 x_EG, y_EG, z_EG, quat0, quatx, quaty, quatz] = ...
     SixDoFQuatVab(t_end, state0, ...
                   myAircraft, ...
                   delta_T_law, ...
                   delta_e_deg_law, delta_s_deg_law, ...
                   delta_a_deg_law, delta_r_deg_law);

Nt = length(time);

stackedPlot4(time, ...
             delta_T, delta_e_deg, delta_a_deg, delta_r_deg, ...
             {"Simulation time (s)", ...
              "$\delta_\mathrm{T}$", "$\delta_\mathrm{e}$ (deg)", ...
              "$\delta_\mathrm{a}$ (deg)", "$\delta_\mathrm{r}$ (deg)"}, ...
             {}, {}, 'exf18harvthrustinputcommands.pdf')

alpha_deg = convang(alpha, 'rad', 'deg');
beta_deg = convang(beta, 'rad', 'deg');
stackedPlot3(time, ...
             V, alpha_deg, beta_deg, ...
             {"Simulation time (s)", ...
              "Airspeed (m/s)", "$\alpha_\mathrm{B}$ (deg)", "$\beta$ (deg)"}, ...
             {}, {}, 'exf18harvthrustVab.pdf')

p_degps = convangvel(p, 'rad/s', 'deg/s');
q_degps = convangvel(q, 'rad/s', 'deg/s');
r_degps = convangvel(r, 'rad/s', 'deg/s');
stackedPlot3(time, ...
             p_degps, q_degps, r_degps, ...
             {"Simulation time (s) ", ...
              "$p$ (deg/s)", "$q$ (deg/s)", "$r$ (deg/s)"}, ...
             {}, {}, 'exf18harvthrustangvelcomponents.pdf')

altitude = -z_EG;
stackedPlot3(time, ...
             x_EG, y_EG, altitude, ...
             {"Simulation time (s)", ...
              "$x_{\mathrm{E},G}$ (m)", "$y_{\mathrm{E},G}$ (m)", "Altitude (m)"}, ...
             {}, {}, 'exf18harvthrustcogxyh.pdf')

[psi, theta, phi] = quat2angle([quat0, quatx, quaty, quatz]);
phi_deg = convang(phi, 'rad', 'deg');
theta_deg = convang(theta, 'rad', 'deg');
psi_deg = convang(psi, 'rad', 'deg');
stackedPlot3(time, ...
             phi_deg, theta_deg, psi_deg, ...
             {"Simulation time (s)", ...
              "$\varphi$ (deg)", "$\theta$ (deg)", "$\psi$ (deg)"}, ...
             {}, {}, 'exf18harvthrusteulangles.pdf')

ModelsInputs = [alpha_deg, beta_deg, ...
                delta_T, delta_e_deg, delta_s_deg, delta_a_deg, delta_r_deg, ...
                p_degps, q_degps, r_degps, ...
                altitude, V];
CL = zeros(Nt, 1);
CD = CL;
CC = CL;
CRoll = CL;
CPitch = CL;
CYaw = CL;
Thrust = CL;
[~, sound, ~, ~] = atmosisa(altitude);
Mach = V ./ sound;
for it = 1 : Nt
    CL(it) = myAircraft.LiftCoeffModel(ModelsInputs(it, :));
    CD(it) = myAircraft.DragCoeffModel(ModelsInputs(it, :));
    CC(it) = myAircraft.CrossforceCoeffModel(ModelsInputs(it, :));
    CRoll(it) = myAircraft.RollCoeffModel(ModelsInputs(it, :));
    CPitch(it) = myAircraft.PitchCoeffModel(ModelsInputs(it, :));
    CYaw(it) = myAircraft.YawCoeffModel(ModelsInputs(it, :));
    Thrust(it) = myAircraft.ThrustModel(altitude(it), Mach(it));
end
stackedPlot3(time, ...
             CL, CD, CC, ...
             {"Simulation time (s)", ...
              "$C_L$", "$C_D$", "$C_C$"}, ...
             {}, {}, 'exf18harvthrustaeroforcecoeffhistories.pdf')
stackedPlot3(time, ...
             CRoll, CPitch, CYaw, ...
             {"Simulation time (s)", ...
              "$C_\mathcal{L}$", "$C_\mathcal{M}$", "$C_\mathcal{N}$"}, ...
             {}, {}, 'exf18harvthrustaeromomcoeffhistories.pdf')
stackedPlot2(time, ...
             Mach, 1e-3*Thrust, ...
             {"Simulation time (s)", ...
              "Mach number", "Thrust (kN)"}, ...
             {}, {}, 'exf18harvthrustmachthrust.pdf')

u = V .* cos(beta) .* cos(alpha);
v = V .* sin(beta);
w = V .* cos(beta) .* sin(alpha);
[f_xA, f_yA, f_zA] = LoadFactor(time, u, v, w, alpha_deg, quat0, quatx, quaty, quatz);
multiPlot(time, ...
          "Simulation time (s)", "$f_{z_\mathrm{A}}$", ...
          {}, ...
          'exf18harvthrustloadfactor.pdf', ...
          f_zA)

Thrust = zeros(Nt, 1);
[~, sound, ~, ~] = atmosisa(altitude);
Mach = V ./ sound;
for it = 1 : Nt
    Thrust(it) = myAircraft.ThrustModel(altitude(it), Mach(it));
end

trajectoryView(time, ...
               x_EG, y_EG, z_EG, ...
               phi, theta, psi, ...
               60, 11, ...
               'exf18harvthrusttrajectory.pdf')