% close all; clear; clc
% 
% aircraftDataFileName = 'DSV_Aircraft_data.txt';
% myAircraft = DSVAircraft(aircraftDataFileName);
% 
% airspeeds = 120 : 15 : 300;
% Nv = length(airspeeds);
% 
% altitudes0 = 0 : 3000 : 9000;
% Nh = length(altitudes0);
% 
% deltas_s_deg = -2.0 : 0.5 : 1.0;
% 
% gamma0_deg = 0;
% 
% design0 = [0; 0.5; 0; 0];
% lowerBounds = [convang(-15, 'deg', 'rad'); ...
%                0.0; ...
%                convang(-24, 'deg', 'rad'); ...
%                convang(-3, 'deg', 'rad')];
% upperBounds = [convang(18, 'deg', 'rad'); ...
%                1.0; ...
%                convang(16, 'deg', 'rad'); ...
%                convang(3, 'deg', 'rad')];
% 
% alphas0 = zeros(Nv, Nh, Nd);
% deltas_T0 = alphas0;
% deltas_e0 = alphas0;
% Ntot = Nv * Nh * Nd;
% iteration = 0;
% for iv = 1 : Nv
%     for ih = 1 : Nh
%         for id = 1 : Nd
%             [design, cost] = ...
%                 ThreeDoFTrim(myAircraft, ...
%                              airspeeds(iv), altitudes0(ih), ...
%                              deltas_s_deg(id), gamma0_deg, ...
%                              design0, lowerBounds, upperBounds);
%             alphas0(iv, ih, id) = design(1);
%             deltas_T0(iv, ih, id) = design(2);
%             deltas_e0(iv, ih, id) = design(3);
%             iteration = iteration + 1;
%             fprintf("Iteration %d/%d\n", iteration, Ntot)
%         end
%     end
% end
% 
% alphas0_deg = convang(alphas0, 'rad', 'deg');
% deltas_e0_deg = convang(deltas_e0, 'rad', 'deg');

altitude_titles = cell(Nh-1, 1);
for ih = 1 : Nh-1
    altitude_titles{ih} = strcat( ...
        "$h = ", num2str(altitudes0(ih+1)), "$ m");
end

delta_s_labels = cell(Nd, 1);
for id = 1 : Nd
    delta_s_labels{id} = strcat( ...
        "$\delta_\mathrm{s} = ", num2str(deltas_s_deg(id)), "$ deg");
end

stackedPlot3(airspeeds, ...
             alphas0_deg(:, 1, :), ...
             deltas_T0(:, 1, :), ...
             deltas_e0_deg(:, 1, :), ...
             {"$V_{G,0}$ (m/s)", "$\alpha_0$ (deg)", ...
              "$\delta_{\mathrm{e},0}$ (deg)", ...
              "$\delta_{\mathrm{T},0}$ (deg)"}, ...
             {strcat("$h = ", num2str(altitudes0(1)), "$ m"), "", ""}, ...
             delta_s_labels, 'ex3dofTtrimsh0.pdf')

stackedPlot3(airspeeds, ...
             alphas0_deg(:, 2, :), ...
             alphas0_deg(:, 3, :), ...
             alphas0_deg(:, 4, :), ...
             {"$V_{G,0}$ (m/s)", "$\alpha_0$ (deg)", ...
              "$\alpha_0$ (deg)", "$\alpha_0$ (deg)"}, ...
             altitude_titles, delta_s_labels, 'ex3dofTalphas.pdf')

stackedPlot3(airspeeds, ...
             deltas_T0(:, 2, :), ...
             deltas_T0(:, 3, :), ...
             deltas_T0(:, 4, :), ...
             {"$V_{G,0}$ (m/s)", "$\delta_{\mathrm{T},0}$ (deg)", ...
              "$\delta_{\mathrm{T},0}$ (deg)", ...
              "$\delta_{\mathrm{T},0}$ (deg)"}, ...
             altitude_titles, delta_s_labels, 'ex3dofTdeltast.pdf')

stackedPlot3(airspeeds, ...
             deltas_e0_deg(:, 2, :), ...
             deltas_e0_deg(:, 3, :), ...
             deltas_e0_deg(:, 4, :), ...
             {"$V_{G,0}$ (m/s)", "$\delta_{\mathrm{e},0}$ (deg)", ...
              "$\delta_{\mathrm{e},0}$ (deg)", ...
              "$\delta_{\mathrm{e},0}$ (deg)"}, ...
             altitude_titles, delta_s_labels, 'ex3dofTdeltase.pdf')

% t_end = 30;
% 
% alpha0 = design(1);
% delta_T0 = design(2);
% delta_e0_deg = convang(design(3), 'rad', 'deg');
% delta_s0_deg = convang(design(4), 'rad', 'deg');
% 
% elevation0 = alpha0 - myAircraft.mu_x + ...
%                             convang(gamma0_deg, 'deg', 'rad');
% state0 = [airspeed, alpha0, 0, 0, -altitude0, elevation0].';
% 
% delta_T_law = @(t) interp1([0, 1] * t_end, ...
%                            [1, 1] * delta_T0, ...
%                             t, 'linear');
% 
% delta_e_deg_law = @(t) interp1([0, 1] * t_end, ...
%                                [1, 1] * delta_e0_deg, ...
%                                 t, 'linear');
% 
% delta_s_deg_law = @(t) interp1([0, 1] * t_end, ...
%                                [1, 1] * delta_s0_deg, ...
%                                 t, 'linear');
% 
% [time, ...
%  delta_T, delta_e_deg, delta_s_deg, ...
%  V, alpha, q, x_EG, z_EG, elevation] = ThreeDoFVabLin(t_end, state0, ...
%                                                       myAircraft, ...
%                                                       delta_T_law, ...
%                                                       delta_e_deg_law, ...
%                                                       delta_s_deg_law);
% 
% Nt = length(time);
% 
% stackedPlot2(time, ...
%              delta_T, delta_e_deg, ...
%              {"Simulation time (s)", ...
%               "$\delta_\mathrm{T}$", "$\delta_\mathrm{e}$ (deg)"}, ...
%              {}, {}, 'ex3dofTinputcommands.pdf')
% 
% alpha_deg = convang(alpha, 'rad', 'deg');
% stackedPlot2(time, ...
%              V, alpha_deg, ...
%              {"Simulation time (s)", ...
%               "Airspeed (m/s)", "$\alpha$ (deg)"}, ...
%              {}, {}, 'ex3dofTairspeedAoA.pdf')
% 
% elevation_deg = convang(elevation, 'rad', 'deg');
% q_degps = convangvel(q, 'rad/s', 'deg/s');
% stackedPlot2(time, ...
%              elevation_deg, q_degps, ...
%              {"Simulation time (s)", ...
%               "$\theta$ (deg)", "q (deg/s)"}, ...
%              {}, {}, 'ex3dofTelevationq.pdf')
% 
% stackedPlot2(time, ...
%              x_EG, -z_EG, ...
%              {"Simulation time (s)", ...
%               "$x_{\mathrm{E},G}$ (m)", "Altitude (m)"}, ...
%              {}, {}, 'ex3dofTcogxz.pdf')
% 
% gamma_deg = elevation_deg - ...
%     (alpha_deg - convang(myAircraft.mu_x, 'rad', 'deg'));
% multiPlot(time, ...
%           "Simulation time (s)", "$\gamma$ (deg)", {}, ...
%           'ex3dofgamma.pdf', gamma_deg);
% 
% O = zeros(Nt, 1);
% trajectoryView(time, ...
%                x_EG, O, z_EG, ...
%                O, elevation, O, ...
%                75, 6, ...
%                'ex3dofTtrajectory.pdf')